apiVersion: v1
kind: Service
metadata:
  name: {{ include "quizchecker.fullname" . }}
  labels:
    {{- include "quizchecker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quizchecker.selectorLabels" . | nindent 4 }}
