name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the `main` branch
  pull_request:
    branches:
      - main  # Triggers the workflow when a PR is made to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2

      # Step 3: Log in to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t quizchecker:latest .

      # Step 5: Tag the image with the ECR repository URI
      - name: Tag Docker image for ECR
        run: |
          docker tag quizchecker:latest ${{ vars.AWS_ECR_REPOSITORY_URI }}/quizchecker:latest

      # Step 6: Push the image to AWS ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ vars.AWS_ECR_REPOSITORY_URI }}/quizchecker:latest
